import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './components/**/*.{js,vue,ts}',
    './**/*.vue',
  ],
  theme: {
    extend: {
      borderRadius: {
        'primitive-0': 'var(--ds-rounding-primitive-0)',
        'primitive-4': 'var(--ds-rounding-primitive-4)',
        'primitive-6': 'var(--ds-rounding-primitive-6)',
        'primitive-8': 'var(--ds-rounding-primitive-8)',
        'primitive-10': 'var(--ds-rounding-primitive-10)',
        'primitive-12': 'var(--ds-rounding-primitive-12)',
        'primitive-16': 'var(--ds-rounding-primitive-16)',
        'primitive-20': 'var(--ds-rounding-primitive-20)',
        'primitive-24': 'var(--ds-rounding-primitive-24)',
        'primitive-32': 'var(--ds-rounding-primitive-32)',
        'primitive-max': 'var(--ds-rounding-primitive-max)',

        'container-xxs': 'var(--ds-rounding-container-xxs)',
        'container-xs': 'var(--ds-rounding-container-xs)',
        'container-md': 'var(--ds-rounding-container-md)',
        'container-lg': 'var(--ds-rounding-container-lg)',
        'container-xl': 'var(--ds-rounding-container-xl)',
        'container-2xl': 'var(--ds-rounding-container-2xl)',
        'container-3xl': 'var(--ds-rounding-container-3xl)',
        'modal-md': 'var(--ds-rounding-modal-md)',

        'button-sm': 'var(--ds-rounding-button-sm)',
        'button-md': 'var(--ds-rounding-button-md)',
        'button-xl': 'var(--ds-rounding-button-xl)',
        'dropdown': 'var(--ds-rounding-component-dropdown)',
        'input-xl': 'var(--ds-rounding-component-input-xl)',
        'badge': 'var(--ds-rounding-component-badge)',
        'tag': 'var(--ds-rounding-component-tag)',
        'checkbox': 'var(--ds-rounding-component-checkbox)',
        'radio': 'var(--ds-rounding-component-radio)',
        'switch': 'var(--ds-rounding-component-switch)',
        'tooltip': 'var(--ds-rounding-component-tooltip)',
        'avatar': 'var(--ds-rounding-component-avatar)',
        'calendar-selector': 'var(--ds-rounding-component-calendar-selector)',
      },
      colors: {
        'brand': {
          50: 'var(--ds-color-primitive-brand-50)',
          100: 'var(--ds-color-primitive-brand-100)',
          150: 'var(--ds-color-primitive-brand-150)',
          200: 'var(--ds-color-primitive-brand-200)',
          300: 'var(--ds-color-primitive-brand-300)',
          400: 'var(--ds-color-primitive-brand-400)',
          500: 'var(--ds-color-primitive-brand-500)',
          600: 'var(--ds-color-primitive-brand-600)',
          700: 'var(--ds-color-primitive-brand-700)',
          DEFAULT: 'var(--ds-color-brand-default)',
          hover: 'var(--ds-color-brand-hover)',
          active: 'var(--ds-color-brand-active)',
          light: 'var(--ds-color-brand-light)',
          accent: {
            DEFAULT: 'var(--ds-color-brand-accent-default)',
            hover: 'var(--ds-color-brand-accent-hover)',
            active: 'var(--ds-color-brand-accent-active)',
            disabled: 'var(--ds-color-brand-accent-disabled)',
          },
        },
        'light': {
          100: 'var(--ds-color-primitive-light-100)',
          200: 'var(--ds-color-primitive-light-200)',
          300: 'var(--ds-color-primitive-light-300)',
          400: 'var(--ds-color-primitive-light-400)',
          450: 'var(--ds-color-primitive-light-450)',
          500: 'var(--ds-color-primitive-light-500)',
          600: 'var(--ds-color-primitive-light-600)',
        },
        'red': {
          100: 'var(--ds-color-primitive-red-100)',
          250: 'var(--ds-color-primitive-red-250)',
          400: 'var(--ds-color-primitive-red-400)',
          500: 'var(--ds-color-primitive-red-500)',
          600: 'var(--ds-color-primitive-red-600)',
          700: 'var(--ds-color-primitive-red-700)',
          800: 'var(--ds-color-primitive-red-800)',
        },
        'green': {
          100: 'var(--ds-color-primitive-green-100)',
          200: 'var(--ds-color-primitive-green-200)',
          600: 'var(--ds-color-primitive-green-600)',
          700: 'var(--ds-color-primitive-green-700)',
        },
        'blue': {
          100: 'var(--ds-color-primitive-blue-100)',
          200: 'var(--ds-color-primitive-blue-200)',
          600: 'var(--ds-color-primitive-blue-600)',
          700: 'var(--ds-color-primitive-blue-700)',
        },
        'grey': {
          100: 'var(--ds-color-primitive-grey-100)',
          200: 'var(--ds-color-primitive-grey-200)',
          300: 'var(--ds-color-primitive-grey-300)',
          400: 'var(--ds-color-primitive-grey-400)',
          500: 'var(--ds-color-primitive-grey-500)',
          600: 'var(--ds-color-primitive-grey-600)',
          700: 'var(--ds-color-primitive-grey-700)',
          800: 'var(--ds-color-primitive-grey-800)',
          900: 'var(--ds-color-primitive-grey-900)',
          950: 'var(--ds-color-primitive-grey-950)',
        },
        'alpha-white': {
          8: 'var(--ds-color-primitive-alpha-white-8)',
          16: 'var(--ds-color-primitive-alpha-white-16)',
          24: 'var(--ds-color-primitive-alpha-white-24)',
          32: 'var(--ds-color-primitive-alpha-white-32)',
          64: 'var(--ds-color-primitive-alpha-white-64)',
          80: 'var(--ds-color-primitive-alpha-white-80)',
        },
        'control': {
          primary: {
            'DEFAULT': 'var(--ds-color-control-primary-default)',
            'hover': 'var(--ds-color-control-primary-hover)',
            'active': 'var(--ds-color-control-primary-active)',
            'focus': 'var(--ds-color-control-primary-focus)',
            'focus-border': 'var(--ds-color-control-primary-focus-border)',
            'disabled': 'var(--ds-color-control-primary-disabled)',
            'elevate': 'var(--ds-color-control-primary-elevate)',
          },
          accent: {
            'DEFAULT': 'var(--ds-color-control-accent-default)',
            'hover': 'var(--ds-color-control-accent-hover)',
            'active': 'var(--ds-color-control-accent-active)',
            'focus': 'var(--ds-color-control-accent-focus)',
            'focus-border': 'var(--ds-color-control-accent-focus-border)',
            'disabled': 'var(--ds-color-control-accent-disabled)',
            'elevate': 'var(--ds-color-control-accent-elevate)',
            'border': 'var(--ds-color-control-accent-border)',
          },
          secondary: {
            DEFAULT: 'var(--ds-color-control-secondary-default)',
            hover: 'var(--ds-color-control-secondary-hover)',
            active: 'var(--ds-color-control-secondary-active)',
            disabled: 'var(--ds-color-control-secondary-disabled)',
            elevate: 'var(--ds-color-control-secondary-elevate)',
            border: 'var(--ds-color-control-secondary-border)',
          },
          input: {
            'DEFAULT': 'var(--ds-color-control-input-default)',
            'hover': 'var(--ds-color-control-input-hover)',
            'focus-border': 'var(--ds-color-control-input-focus-border)',
            'disabled': 'var(--ds-color-control-input-disabled)',
            'elevate': 'var(--ds-color-control-input-elevate)',
            'elevate-active': 'var(--ds-color-control-input-elevate-active)',
            'elevate-filled': 'var(--ds-color-control-input-elevate-filled)',
            'border': 'var(--ds-color-control-input-border)',
          },
        },
        'border': {
          'primary': 'var(--ds-color-border-primary)',
          'secondary': 'var(--ds-color-border-secondary)',
          'tertiary': 'var(--ds-color-border-tertiary)',
          'quaternary': 'var(--ds-color-border-quaternary)',
          'white': 'var(--ds-color-border-white)',
          'brand': 'var(--ds-color-border-brand)',
          'brand-light': 'var(--ds-color-border-brand-light)',
        },

        'bg': {
          primary: 'var(--ds-color-bg-primary)',
          secondary: 'var(--ds-color-bg-secondary)',
          tertiary: 'var(--ds-color-bg-tertiary)',
          quaternary: 'var(--ds-color-bg-quaternary)',
          dark: 'var(--ds-color-bg-dark)',
          elevated: 'var(--ds-color-bg-elevated)',
          scrim: 'var(--ds-color-bg-scrim)',
        },
        'sentiment': {
          negative: {
            'fg': 'var(--ds-color-sentiment-negative-fg)',
            'fg-hover': 'var(--ds-color-sentiment-negative-fg-hover)',
            'fg-tint': 'var(--ds-color-sentiment-negative-fg-tint)',
            'bg': 'var(--ds-color-sentiment-negative-bg)',
            'bg-hover': 'var(--ds-color-sentiment-negative-bg-hover)',
            'bg-tint': 'var(--ds-color-sentiment-negative-bg-tint)',
          },
          informative: {
            DEFAULT: 'var(--ds-color-sentiment-informative-defalut)',
            hover: 'var(--ds-color-sentiment-informative-hover)',
            bg: 'var(--ds-color-sentiment-informative-bg)',
          },
          positive: {
            DEFAULT: 'var(--ds-color-sentiment-positive-defalut)',
            hover: 'var(--ds-color-sentiment-positive-hover)',
            bg: 'var(--ds-color-sentiment-positive-bg)',
          },
          warning: {
            DEFAULT: 'var(--ds-color-sentiment-warning-defalut)',
            hover: 'var(--ds-color-sentiment-warning-hover)',
            bg: 'var(--ds-color-sentiment-warning-bg)',
          },
        },
        'chart': {
          50: 'var(--ds-charts-50)',
          100: 'var(--ds-charts-100)',
          150: 'var(--ds-charts-150)',
          200: 'var(--ds-charts-200)',
          250: 'var(--ds-charts-250)',
          300: 'var(--ds-charts-300)',
          350: 'var(--ds-charts-350)',
          400: 'var(--ds-charts-400)',
          450: 'var(--ds-charts-450)',
          500: 'var(--ds-charts-500)',
          550: 'var(--ds-charts-550)',
          600: 'var(--ds-charts-600)',
          650: 'var(--ds-charts-650)',
        },
        'ui': {
          'text-highlighted': 'var(--ui-text-highlighted)',
          'bg': 'var(--ui-bg)',
        },
      },
      size: {
        'control-input-lg': 'var(--ds-size-control-input-lg)',
        'control-button-sm': 'var(--ds-size-control-button-sm)',
        'control-button-md': 'var(--ds-size-control-button-md)',
        'control-button-xl': 'var(--ds-size-control-button-xl)',
        'modal-md-width': 'var(--ds-size-modal-md-width)',
        'modal-lg-width': 'var(--ds-size-modal-lg-width)',
        'modal-mobile': 'var(--ds-size-modal-mobile)',
        'tooltip-width-max': 'var(--ds-size-tooltip-width-max)',
      },
    },
  },
}

export default config
